val mvp : int
val atomics : int
val bulk_memory : int
val mutable_globals : int
val nontrapping_fp_to_int : int
val sign_ext : int
val simd128 : int
val exception_handling : int
val tail_call : int
val reference_types : int
val multivalue : int
val all : int
